// resources/assets/frontend/src/components/SignIn.vue
<template>
  <div>
    <form @submit.prevent="onSignIn">
      <div class="form-group">
        <label for="email">Email Address:</label>
        <input id="email"
               name="email" required
               type="user.email"
               class="form-control"
               v-model="user.email"
        >
      </div>
      <div class="alert alert-danger" v-if="false">
        <strong>Danger!</strong> Please enter a proper email address.
      </div>
      <div class="form-group">
        <label for="pwd">Password:</label>
        <input id="pwd"
               name="password"
               type="password"
               class="form-control"
               v-model="user.password"
        >
      </div>
      <div class="alert alert-danger" v-if="false">
        <strong>Danger!</strong> Your password is required.
      </div>
      <!--<div class="checkbox">-->
      <!--<label><input type="checkbox"> Remember me</label>-->
      <!--</div>-->
      <button class="btn btn-primary">SIGN IN</button>
      <button type="reset" class="btn btn-default" @click="onReset">RESET</button>
    </form>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        user: {
          email: '',
          password: ''
        }
      }
    },
    methods: {
      onSignIn () {
        console.log('User Sign In Details : ', this.user);
      },
      onReset () {
        this.user.email = '';
        this.user.password = '';
      }
    }
  }
</script>

// src/app/sign-in/sign-in.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Response } from '@angular/http';

import { AuthService } from '../auth.service';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.css']
})
export class SignInComponent implements OnInit {

  constructor( private authService: AuthService ) { }

  ngOnInit() { }

  onSignIn(formSignIn: NgForm) {
    const body = {
      email: formSignIn.value.email,
      password: formSignIn.value.password
    };
    this.authService.signin(body)
      .subscribe(
        (response: Response) => {
          localStorage.setItem('token', response.json().token);
          alert(response.json().message);
          },
        (error: Response) => console.log(error),
        () => formSignIn.reset()
      );
  }

  onReset(formSignIn: NgForm) {
    formSignIn.reset();
  }

}

<form #form="ngForm" (ngSubmit)="onSignIn(form)">
    <div class="form-group">
        <label for="email">Email Address:</label>
        <input
            id="email"
            class="form-control"
            name="email"
            email
            ngModel
            required
            #email="ngModel"
        >
    </div>
    <p class="text-danger" *ngIf="email.invalid && email.touched">
        Please enter a proper email address.
    </p>
    <div class="form-group">
        <label for="pwd">Password:</label>
        <input
            id="pwd"
            type="password"
            class="form-control"
            name="password"
            ngModel
            required
            #password="ngModel"
        >
    </div>
    <p class="text-danger" *ngIf="password.invalid && password.touched">
        Your password is required.
    </p>
    <!--<div class="checkbox">-->
    <!--<label><input type="checkbox"> Remember me</label>-->
    <!--</div>-->
    <button class="btn btn-primary" [disabled]="form.invalid">SIGN IN</button>
    <button type="reset" class="btn btn-default" (click)="onReset(form)">
        RESET
    </button>
</form>
