// resources/assets/frontend/src/components/NewQuote.vue
<template>
  <div>
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">New Quote</div>
        <div class="panel-body">
          <form @submit.prevent="onSubmit">
            <label for="content">New Content:</label>
            <input id="content"
                   type="text"
                   name="content"
                   v-model="context"
            >
            <button class="btn btn-primary btn-sm" type="submit">Save</button>
            <button class="btn btn-default btn-sm" type="reset" @click="onCancel">Cancel</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        context: ''
      }
    },
    methods: {
      onCancel () {
        this.context = '';
        console.log('ON FETCH QUOTES CLICKED');
      },
      onSubmit () {
        console.log('FORM SUBMITTED', this.context);
      }
    }
  }
</script>

// src/app/new-quote/new-quote.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-new-quote',
  templateUrl: './new-quote.component.html',
  styleUrls: ['./new-quote.component.css']
})
export class NewQuoteComponent implements OnInit {

  constructor() { }

  ngOnInit() { }

  onSave() {
    console.log('New Component Save Button Clicked');
  }

  onCancel() {
    console.log('New Component Cancel Button Clicked');
  }

}

<div class="panel-group">
  <div class="panel panel-primary">
    <div class="panel-heading">New Quote</div>
    <div class="panel-body">
      <label for="content">New Content:</label>
      <input id="content" type="text">
      <button class="btn btn-primary btn-sm" (click)="onSave()">Save</button>
      <button class="btn btn-default btn-sm" (click)="onCancel()">Cancel</button>
    </div>
  </div>
</div>
