// src/app/quote/quote.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { QuoteModel } from "../quote.model";

@Component({
  selector: 'app-quote',
  templateUrl: './quote.component.html',
  styleUrls: ['./quote.component.css']
})
export class QuoteComponent implements OnInit {

  editMode = false;
  @Input() quote: QuoteModel;

  constructor() { }

  ngOnInit() { }

  onEdit() {
    this.editMode = true;
  }

  onCancel() {
    this.editMode = false;
  }

  onSave() {
    this.editMode = false;
  }

  onDelete() {
    console.log('Delete Button Pressed!');
  }

}

<div class="panel-group">
  <div class="panel panel-primary">
    <div class="panel-heading">{{ quote.content }}</div>
    <div class="panel-body">
      <div class="form-inline" *ngIf="editMode">
        <label for="content">New Content:</label>
        <input id="content" type="text">
        <button class="btn btn-primary btn-sm" (click)="onSave()">Save</button>
        <button class="btn btn-default btn-sm" (click)="onCancel()">Cancel</button>
      </div>
      <div *ngIf="!editMode">
        <button class="btn btn-primary btn-sm" (click)="onEdit()">Edit</button>
        <button class="btn btn-danger btn-sm" (click)="onDelete()">Delete</button>
      </div>
    </div>
  </div>
</div>

// resources/assets/frontend/src/components/Quote.vue
<template>
  <div>
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">{{ quote.content }}</div>
        <div class="panel-body">
          <div class="form-inline" v-if="editMode">
            <label for="content">New Content:</label>
            <input id="content" type="text" v-model="editedValue">
            <button class="btn btn-primary btn-sm" @click="onSave">Save</button>
            <button class="btn btn-default btn-sm" @click="onCancel">Cancel</button>
          </div>
          <div v-if="!editMode">
            <button class="btn btn-primary btn-sm" @click="onEdit">Edit</button>
            <button class="btn btn-danger btn-sm" @click="onDelete">Delete</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    props: ['quote'],
    data () {
      return {
        editMode: false,
        editedValue: ''
      }
    },
    methods: {
      onSave () {
        console.log('ON SAVE CLICKED - NEW CONTENT : ', this.quote);
        this.quote.content = this.editedValue;
        this.editMode = false;
      },
      onCancel () {
        console.log('ON CANCEL CLICKED');
        this.editedValue = '';
        this.editMode = false;
      },
      onEdit () {
        this.editMode = true;
        console.log('ON EDIT CLICKED');
      },
      onDelete () {
        console.log('ON DELETE CLICKED');
        this.editMode = false;
      }
    }
  }
</script>
