// src/app/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Response } from '@angular/http';

import { AuthService } from '../auth.service';


@Component({
  selector: 'app-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.css']
})
export class SignUpComponent implements OnInit {

  constructor( private authService: AuthService ) { }

  ngOnInit() { }

  onSignUp(formSignUp: NgForm) {
    const body = {
      name: formSignUp.value.name,
      email: formSignUp.value.email,
      password: formSignUp.value.password
    };
    this.authService.signup(body)
      .subscribe(
        (response: Response) => {
          alert(response.json().message);
        },
        (error: Response) => console.log(error),
        () => formSignUp.reset()
      );
  }

  onReset(formSignUp: NgForm) {
    formSignUp.reset();
  }

}

<form #form="ngForm" (ngSubmit)="onSignUp(form)">
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" class="form-control" id="name" name="name" ngModel required>
  </div>
  <div class="form-group">
    <label for="email">Email Address:</label>
    <input class="form-control" id="email" email name="email" ngModel required>
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="pwd" name="password" ngModel required>
  </div>
  <!--<div class="checkbox">-->
  <!--<label><input type="checkbox"> Remember Me</label>-->
  <!--</div>-->
  <button type="submit" class="btn btn-primary" [disabled]="form.invalid">SIGN UP</button>
  <button type="text" class="btn btn-default" (click)="onReset(form)">RESET</button>
</form>

// resources/assets/frontend/src/components/SignUp.vue
<template>
  <div>
    <form  @submit="onSignUp">
      <div class="form-group">
        <label for="name">Name:</label>
        <input id="name"
               name="name"
               type="text"
               class="form-control"
               v-model="user.name"
        >
      </div>
      <div>
        <div class="alert alert-danger" v-if="false">
          <strong>Danger!</strong> Your Name is Required!
        </div>
      </div>

      <div class="form-group">
        <label for="email">Email Address:</label>
        <input id="email"
               name="email"
               type="email"
               class="form-control"
               v-model="user.email"
        >
      </div>
      <div v-if="false">
        <div class="alert alert-danger">
          <strong>Danger!</strong> Your Email Address is Required!
        </div>
        <div class="alert alert-danger">
          <strong>Danger!</strong> Please Enter a Proper Email Address!
        </div>
      </div>

      <div class="form-group">
        <label for="pwd">Password:</label>
        <input id="pwd"
               name="password"
               type="password"
               class="form-control"
               v-model="user.password"
        >
      </div>
      <div>
        <div class="alert alert-danger" v-if="false">
          <strong>Danger!</strong> Your Password is Required!
        </div>
      </div>

      <div class="form-group">
        <label for="cnf_pwd">Confirm Password:</label>
        <input id="cnf_pwd"
               name="cnf_password"
               type="password"
               class="form-control"
               v-model="user.confirmPassword"
        >
      </div>
      <div>
        <div class="alert alert-danger" v-if="false">
          <strong>Danger!</strong> Confirming Password is Required!
        </div>
      </div>

      <!--<div class="checkbox">-->
      <!--<label><input type="checkbox"> Remember Me</label>-->
      <!--</div>-->

      <button class="btn btn-primary">SIGN UP</button>
      <button type="reset" class="btn btn-default" @click="onReset">RESET</button>
    </form>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        user: {
          name: '',
          email: '',
          password: '',
          confirmPassword: ''
        }
      }
    },
    methods: {
      onSignUp () {
        console.log('User Sign Up Details : ', this.user);
      },
      onReset () {
        this.user.email = '';
        this.user.password = '';
        this.user.password = '';
        this.user.confirmPassword = '';
      }
    }
  }
</script>
