// resources/assets/frontend/src/app/core/auth/sign-in/sign-in.component.ts
/**
 * Component to login an existing user
 */
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Store } from '@ngrx/store';

import * as fromApp from '../../store/core.reducers';
import * as AuthActions from '../../store/auth/auth.actions';

@Component( {
	selector: 'app-sign-in',
	templateUrl: './sign-in.component.html',
	styleUrls: [ './sign-in.component.css' ]
} )
export class SignInComponent {

	/** Service injection */
	constructor( private store: Store<fromApp.AppState> ) {}

	/** Function call to submit sign in form */
	onSignIn( formSignIn: NgForm ) {
		const body = {
			email: formSignIn.value.email,
			password: formSignIn.value.password
		};
		this.store.dispatch( new AuthActions.SignInAttempt( body ) );
	}

	/** Function call to reset sign in form */
	onReset( formSignIn: NgForm ) {
		formSignIn.reset();
	}

}

<!-- Sign In Form -->
<form #form="ngForm" (ngSubmit)="onSignIn(form)">
	
	<!-- Email -->
    <div class="form-group">
        <label for="email">Email Address:</label>
        <input
            id="email"
            class="form-control"
            name="email"
            email
            ngModel
            required
            #email="ngModel"
        >
    </div>
	<div class="alert alert-danger" *ngIf="email.invalid && email.touched">
        <strong>Danger!</strong> Please enter a proper email address.
    </div>
	
	<!-- Password -->
	<div class="form-group">
        <label for="pwd">Password:</label>
        <input
            id="pwd"
            type="password"
            class="form-control"
            name="password"
            ngModel
            required
            #password="ngModel"
        >
    </div>
	<div class="alert alert-danger" *ngIf="password.invalid && password.touched">
		<strong>Danger!</strong> Your password is required.
	</div>
 
	<!--<div class="checkbox">-->
    <!--<label><input type="checkbox"> Remember me</label>-->
    <!--</div>-->
    
	<!-- Submit & Reset Button -->
	<button class="btn btn-primary" [disabled]="form.invalid">SIGN IN</button>
    <button type="reset" class="btn btn-default" (click)="onReset(form)">RESET</button>
</form>

// resources/assets/frontend/src/components/SignIn.vue
<template>
  <div>
    <form @submit.prevent="onSignIn">
      <div class="form-group">
        <label for="email">Email Address:</label>
        <input id="email"
               name="email" required
               type="user.email"
               class="form-control"
               v-model="user.email"
        >
      </div>
      <div class="alert alert-danger" v-if="false">
        <strong>Danger!</strong> Please enter a proper email address.
      </div>
      <div class="form-group">
        <label for="pwd">Password:</label>
        <input id="pwd"
               name="password"
               type="password"
               class="form-control"
               v-model="user.password"
        >
      </div>
      <div class="alert alert-danger" v-if="false">
        <strong>Danger!</strong> Your password is required.
      </div>
      <!--<div class="checkbox">-->
      <!--<label><input type="checkbox"> Remember me</label>-->
      <!--</div>-->
      <button class="btn btn-primary">SIGN IN</button>
      <button type="reset" class="btn btn-default" @click="onReset">RESET</button>
    </form>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        user: {
          email: '',
          password: ''
        }
      }
    },
    methods: {
      onSignIn () {
        this.$store.dispatch('userSignIn', this.user);
      },
      onReset () {
        this.user.email = '';
        this.user.password = '';
      }
    }
  }
</script>
