// resources/assets/frontend/src/app/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';

import { AuthService } from '../auth.service';
import { HttpErrorResponse } from '@angular/common/http';


@Component( {
	selector : 'app-sign-up',
	templateUrl : './sign-up.component.html',
	styleUrls : [ './sign-up.component.css' ]
} )
export class SignUpComponent implements OnInit {
	
	formSignUp: FormGroup;
	
	constructor( private authService: AuthService ) {   }
	
	ngOnInit() {

		this.formSignUp = new FormGroup( {
			'name' : new FormControl( null, Validators.required ),
			'email' : new FormControl( null, [ Validators.required, Validators.email ] ),
			'password' : new FormControl( null, Validators.required ),
			'cnf_password' : new FormControl( null, Validators.required )
		} );

	}
	
	// confirmPasswordValidator( control: FormControl ): { [ s: string ]: boolean } {
	// 	 const pwd = this.formSignUp.get('password').value;
	// 	// const pwd = control.get('password').value;
	// 	const cnf_pwd = control.value;
	// 	if(pwd !== cnf_pwd) {
	// 		return { 'confirmPasswordValidator': true };
	// 	}
	// 	return null;this.confirmPasswordValidator.bind(this)
	// }
	
	onSignUp() {

		const body = this.formSignUp.value;

		this.authService.signup( body )
		.subscribe(
			( res: { success: boolean, message: string } ) => {
				alert( res.message );
			},
			( err: HttpErrorResponse ) => console.log( err ),
			() => this.formSignUp.reset()
		);

	}
	
	onReset() {

		this.formSignUp.reset();

	}
	
}

<form  [formGroup]="formSignUp" (ngSubmit)="onSignUp()">
	<div class="form-group">
		<label for="name">Name:</label>
		<input
			id="name"
			name="name"
			class="form-control"
			formControlName="name"
		>
	</div>
	<div *ngIf="formSignUp.get('name').invalid && formSignUp.get('name').touched">
		<div class="alert alert-danger" *ngIf="formSignUp.get('name').errors.required">
			<strong>Danger!</strong> Your Name is Required!
		</div>
	</div>
	
	<div class="form-group">
		<label for="email">Email Address:</label>
		<input
			id="email"
			name="email"
			class="form-control"
			formControlName="email"
		>
	</div>
	<div *ngIf="formSignUp.get('email').invalid && formSignUp.get('email').touched">
		<div class="alert alert-danger" >
			<div *ngIf="formSignUp.get('email').errors.required">
				<strong>Danger!</strong> Your Email Address is Required!
			</div>
			<div *ngIf="formSignUp.get('email').errors.email">
				<strong>Danger!</strong> Please Enter a Proper Email Address!
			</div>
		</div>
	</div>
	
	<div class="form-group">
		<label for="pwd">Password:</label>
		<input
			id="pwd"
			name="password"
			type="password"
			class="form-control"
			formControlName="password"
		>
	</div>
	<div *ngIf="formSignUp.get('password').invalid && formSignUp.get('password').touched">
		<div class="alert alert-danger" *ngIf="formSignUp.get('password').errors.required">
			<strong>Danger!</strong> Your Password is Required!
		</div>
	</div>
	
	<div class="form-group">
		<label for="cnf_pwd">Confirm Password:</label>
		<input
			id="cnf_pwd"
			name="cnf_password"
			type="password"
			class="form-control"
			formControlName="cnf_password"
		>
	</div>
	<div *ngIf="formSignUp.get('cnf_password').invalid && formSignUp.get('cnf_password').touched">
		<div class="alert alert-danger" >
			<div *ngIf="formSignUp.get('cnf_password').hasError('required')">
				<strong>Danger!</strong> Confirm password is Required!
			</div>
			<div *ngIf="formSignUp.get('cnf_password').hasError('confirmPassword')">
				<strong>Danger!</strong> Confirm Password did not Match!
			</div>
		</div>
	</div>
	
	<!--<div *ngIf="formSignUp.get('cnf_password').invalid && formSignUp.get('cnf_password').touched">-->
		<!--<div class="alert alert-danger" *ngIf="formSignUp.get('cnf_password').errors.required">-->
			<!--<strong>Danger!</strong> Confirming Password is Required!-->
		<!--</div>-->
	<!--</div>-->
	
	<!--<div class="checkbox">-->
	<!--<label><input type="checkbox"> Remember Me</label>-->
	<!--</div>-->
	
	<button class="btn btn-primary" [disabled]="false">SIGN UP</button>
	<button type="reset" class="btn btn-default" (click)="onReset()">RESET</button>
</form>

// resources/assets/frontend/src/components/SignUp.vue
<template>
  <div>
    <form  @submit="onSignUp">
      <div class="form-group">
        <label for="name">Name:</label>
        <input id="name"
               name="name"
               type="text"
               class="form-control"
               v-model="user.name"
        >
      </div>
      <div>
        <div class="alert alert-danger" v-if="false">
          <strong>Danger!</strong> Your Name is Required!
        </div>
      </div>

      <div class="form-group">
        <label for="email">Email Address:</label>
        <input id="email"
               name="email"
               type="email"
               class="form-control"
               v-model="user.email"
        >
      </div>
      <div v-if="false">
        <div class="alert alert-danger">
          <strong>Danger!</strong> Your Email Address is Required!
        </div>
        <div class="alert alert-danger">
          <strong>Danger!</strong> Please Enter a Proper Email Address!
        </div>
      </div>

      <div class="form-group">
        <label for="pwd">Password:</label>
        <input id="pwd"
               name="password"
               type="password"
               class="form-control"
               v-model="user.password"
        >
      </div>
      <div>
        <div class="alert alert-danger" v-if="false">
          <strong>Danger!</strong> Your Password is Required!
        </div>
      </div>

      <div class="form-group">
        <label for="cnf_pwd">Confirm Password:</label>
        <input id="cnf_pwd"
               name="cnf_password"
               type="password"
               class="form-control"
               v-model="user.confirmPassword"
        >
      </div>
      <div>
        <div class="alert alert-danger" v-if="false">
          <strong>Danger!</strong> Confirming Password is Required!
        </div>
      </div>

      <!--<div class="checkbox">-->
      <!--<label><input type="checkbox"> Remember Me</label>-->
      <!--</div>-->

      <button class="btn btn-primary">SIGN UP</button>
      <button type="reset" class="btn btn-default" @click="onReset">RESET</button>
    </form>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        user: {
          name: '',
          email: '',
          password: '',
          confirmPassword: ''
        }
      }
    },
    methods: {
      onSignUp () {
        console.log('User Sign Up Details : ', this.user);
      },
      onReset () {
        this.user.email = '';
        this.user.password = '';
        this.user.password = '';
        this.user.confirmPassword = '';
      }
    }
  }
</script>
