// resources/assets/frontend/src/components/Quote.vue
<template>
  <div>
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">{{ quote.content }}</div>
        <div class="panel-body">
          <div class="form-inline" v-if="editMode">
            <label for="content">New Content:</label>
            <input id="content" type="text" v-model="editedValue">
            <button class="btn btn-primary btn-sm" @click="onSave">Save</button>
            <button class="btn btn-default btn-sm" @click="onCancel">Cancel</button>
          </div>
          <div v-if="!editMode">
            <button class="btn btn-primary btn-sm" @click="onEdit">Edit</button>
            <button class="btn btn-danger btn-sm" @click="onDelete">Delete</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    props: ['quote'],
    data () {
      return {
        editMode: false,
        editedValue: ''
      }
    },
    methods: {
      onSave () {
        console.log('ON SAVE CLICKED - NEW CONTENT ');
        const payload = {
          data: {
            content: this.editedValue
          },
          id: this.quote.id
        };
        this.$store.dispatch('editQuote', payload);
        this.editedValue = '';
        this.editMode = false;
      },
      onCancel () {
        console.log('ON CANCEL CLICKED');
        this.editedValue = '';
        this.editMode = false;
      },
      onEdit () {
        this.editMode = true;
        console.log('ON EDIT CLICKED');
      },
      onDelete () {
        const payload = {
          id: this.quote.id
        };
        this.$store.dispatch('deleteQuote', payload);
        this.editMode = false;
      }
    }
  }
</script>

// resources/assets/frontend/src/app/quote/quote.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';

import { QuoteModel } from '../quote.model';
import { QuoteService } from '../quote.service';
import { AuthService } from '../auth.service';

@Component( {
	selector: 'app-quote',
	templateUrl: './quote.component.html',
	styleUrls: [ './quote.component.css' ]
} )
export class QuoteComponent implements OnInit {

	editMode = false;
	editedValue = '';

	@Input() quote: QuoteModel;

	constructor( private authService: AuthService,
	             private quoteService: QuoteService ) { }

	ngOnInit() { }

	onEdit() {

		this.editMode = true;

	}

	onCancel() {

		this.editMode = false;
		this.editedValue = '';

	}

	onSave() {

		const token = this.authService.getToken();
		const obj = {
			content: this.editedValue
		};

		this.quoteService.editQuote( this.quote.id, obj, token )
			.subscribe(
				( res: { success: boolean, message: string } ) => {
					this.quoteService.quotesNeedToUpdate.next();
					alert( res.message );
				},
				( err: HttpErrorResponse ) => console.log( err ),
				() => {
					this.editMode = false;
					this.editedValue = '';
				}
			);

	}

	onDelete() {

		const token = this.authService.getToken();
		this.quoteService.deleteQuote( this.quote.id, token )
			.subscribe(
				( response: { success: boolean, message: string } ) => {
					this.quoteService.quotesNeedToUpdate.next();
					alert( response.message );
				},
				( error: HttpErrorResponse ) => console.log( error )
			);

	}

}

<div class="panel-group">
  <div class="panel panel-primary">
    <div class="panel-heading">{{ quote.content }}</div>
    <div class="panel-body">
      <div class="form-inline" *ngIf="editMode">
        <label for="content">New Content:</label>
        <input id="content" type="text" [(ngModel)]="editedValue">
        <button class="btn btn-primary btn-sm" (click)="onSave()">Save</button>
        <button class="btn btn-default btn-sm" (click)="onCancel()">Cancel</button>
      </div>
      <div *ngIf="!editMode">
        <button class="btn btn-primary btn-sm" (click)="onEdit()">Edit</button>
        <button class="btn btn-danger btn-sm" (click)="onDelete()">Delete</button>
      </div>
    </div>
  </div>
</div>
