// resources/assets/frontend/src/components/NewQuote.vue
<template>
  <div>
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">New Quote</div>
        <div class="panel-body">
          <form @submit.prevent="onSubmit">
            <label for="content">New Content:</label>
            <input id="content"
                   type="text"
                   name="content"
                   v-model="content"
            >
            <button class="btn btn-primary btn-sm" type="submit">Save</button>
            <button class="btn btn-default btn-sm" type="reset" @click="onCancel">Cancel</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        content: ''
      }
    },
    methods: {
      onCancel () {
        this.context = '';
        console.log('ON FETCH QUOTES CLICKED');
      },
      onSubmit () {
        this.$store.dispatch('addQuote', { content: this.content });
      }
    }
  }
</script>

// resources/assets/frontend/src/app/new-quote/new-quote.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { NgForm } from '@angular/forms';

import { QuoteService } from '../quote.service';
import { AuthService } from '../auth.service';

@Component( {
	selector: 'app-new-quote',
	templateUrl: './new-quote.component.html',
	styleUrls: [ './new-quote.component.css' ]
} )
export class NewQuoteComponent implements OnInit {

	constructor( private quoteService: QuoteService, private authService: AuthService ) { }

	ngOnInit() { }

	onCancel( form: NgForm ) {
		form.reset();
	}

	onSubmit( form: NgForm ) {
		const obj = {
			content: form.value.content
		};
		const token = this.authService.getToken();
		this.quoteService.addQuote( obj, token )
			.subscribe(
				( res: { success: boolean, message: string } ) => {
					alert( res.message );
				},
				( err: HttpErrorResponse ) => console.log( err ),
				() => form.reset()
			);
	}

}

<div class="panel-group">
  <div class="panel panel-primary">
    <div class="panel-heading">New Quote</div>
    <div class="panel-body">
      <form #form="ngForm" (ngSubmit)="onSubmit(form)">
        <label for="content">New Content:</label>
        <input id="content" type="text" name="content" ngModel>
        <button class="btn btn-primary btn-sm" type="submit">Save</button>
        <button class="btn btn-default btn-sm" type="button" (click)="onCancel(form)">Cancel</button>
      </form>
    </div>
  </div>
</div>
