// resources/assets/frontend/src/components/Header.vue
<template>
  <div class="row">
    <div class="col-xs-12">
      <ul class="nav nav-tabs">
        <router-link :to="route.url" tag="li" active-class="active" v-for="route in routes" :key="route.url" exact><a>{{ route.name }}</a></router-link>
        <li v-if="isLoggedIn"><a @click="onSignOut">Sign Out</a></li>
      </ul>
    </div>
  </div>
</template>

<script>
  export default {
    computed: {
      routes () {
        if(this.isLoggedIn){
          return [
            { name: 'Quotes', url: '/quotes'},
            { name: 'Add New Quotes', url: '/new-quote'}
          ];
        }
        return [
          { name: 'Sign Up', url: '/sign-up'},
          { name: 'Sign In', url: '/sign-in'}
        ];
      },
      isLoggedIn () {
        return false;
      }
    },
    methods: {
      onSignOut () {
        console.log('SIGN OUT CLICKED');
      }
    }
  }
</script>

// resources/assets/frontend/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Response } from '@angular/http';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  isLoggedIn: boolean;
  constructor( private authService: AuthService, private router: Router ) { }

  ngOnInit() {
    this.isLoggedIn = this.authService.isAuthenticated();
    this.authService.loggedIn.subscribe(
      () => {
        this.isLoggedIn = this.authService.isAuthenticated();
      }
    );
  }

  onSignOut() {
    const token = this.authService.getToken();
    this.authService.signout(token).subscribe(
      (response: Response) => {
        console.log(response.json().message);
        localStorage.removeItem('token');
      },
      (error: Response) => console.log(error),
      () => {
        this.authService.loggedIn.next();
        this.router.navigate(['/sign-in']);
      }
    );
  }

}

<div class="row">
  <div class="col-xs-12">
    <ul class="nav nav-tabs">
      <li *ngIf="isLoggedIn" routerLinkActive="active"><a routerLink="quotes">Quotes</a></li>
      <li *ngIf="isLoggedIn" routerLinkActive="active"><a routerLink="new-quote">Add New Quote</a></li>
      <li *ngIf="!isLoggedIn" routerLinkActive="active"><a routerLink="sign-in">Sign In</a></li>
      <li *ngIf="!isLoggedIn" routerLinkActive="active"><a routerLink="sign-up">Sign Up</a></li>
      <li *ngIf="isLoggedIn"><a (click)="onSignOut()">Sign Out</a></li>
    </ul>
  </div>
</div>
